mutation getAddress($zipCode: String){
  getAddress(zipCode: $zipCode){
   	postalCode
  	city
    country
    state
    street
    number
    neighborhood
    complement
    reference
    geoCoordinates
  }
}
