query getEstablishment {
  establishments @context(provider: "vtex.avatax-br-service@0.x") {
    id
    activitySector
    icmsTaxPayer
    taxRegime
    entityType
    stateTaxId
    street
    neighborhood
    zipCode
    city
    state
    country
    streetNumber
    complement
    phone
    cnpj
    suframa
    dockId
    dockName
    clientId
    clientSecret
    clientCompanyLocation
  }
}
