query getTaxConfiguration {
  getTaxConfiguration  @context(provider: "vtex.avatax-br-service@0.x"){
      allowExecutionAfterErrors
    authorizationHeader
    integratedAuthentication
    url
  }
}
