mutation setTaxConfigurationMutation($operation: String){
  setTaxConfiguration(operation: $operation) @context(provider: "vtex.avatax-br-service@1.x"){
     minimumQuantityAccumulatedForItems
    decimalDigitsPrecision
    minimumValueAccumulated
    allowMultipleDeliveries
    allowManualPrice
    maxIntOfWhiteLabelSellers
    maskFirstPurchaseData
    recaptchaValidation
  }
}

