mutation updateSettings($settings: SettingsInput) {
  updateSettings(settings: $settings)
    @context(provider: "vtex.avatax-br-service@0.x") {
    useAvalaraSandboxEnv
    clientIdValue
    clientSecretValue
  }
}
