export const activitySectors: { [key: string]: string } = {
  armedForces: 'Forças Armadas',
  auctioneer: 'Leiloeiro',
  audiovisualIndustry: 'Audiovisual',
  bondedWarehouse: 'Depósito Alfandegado',
  broadcastingIndustry: 'Radiodifusão',
  construction: 'Construção Civil',
  coops: 'Cooperativa',
  distributor: 'Distribuidor',
  distributionCenter: 'Centro de Distribuição',
  electricityDistributor: 'Distribuidor de Energia Elétrica',
  energyGeneration: 'Gerador e Produtor De Energia Elétrica',
  extractor: 'Extrator',
  farmCoop: 'Cooperativa de Produtores',
  filmIndustry: 'Indústria Cinematográfica',
  finalConsumer: 'Consumidor Final',
  fuelDistributor: 'Distribuidor de Combustível',
  generalWarehouse: 'Armazem Geral',
  importer: 'Importadora',
  industry: 'Industria',
  itaipubiNacional: 'Itaipu Binacional',
  maritimeService: 'Serviço Marítimo',
  mealSupplier: 'Fornecedor de Refeição',
  nonProfitEntity: 'Entidades sem Fins Lucrativos',
  pharmaDistributor: 'Distribuidor de Medicamento',
  publicAgency: 'Orgão Publico',
  religiousEstablishment: 'Templos de Qualquer Culto',
  retail: 'Varejo',
  ruralProducer: 'Produtor Rural',
  securityPublicAgency: 'Agência Pública de Segurança Brasileira',
  service: 'Serviço',
  stockWarehouse: 'Depósito Fechado',
  telco: 'Serviço de Comunicação',
  transporter: 'Transportador/Serviço de Transportadora',
  waterDistributor: 'Distribuidor de Água',
  wholesale: 'Atacado',
}
