import { MessageDescriptor } from 'react-intl'

import { values } from '../definedMessages'

export const activitySectors: { [key: string]: MessageDescriptor } = {
  armedForces: values.activityArmed,
  auctioneer: values.activityAuctioneer,
  audiovisualIndustry: values.activityAudiovisual,
  bondedWarehouse: values.activityWarehouseBonded,
  broadcastingIndustry: values.activityBroadcasting,
  construction: values.activityConstruction,
  coops: values.activityCoops,
  distributor: values.activityDistributor,
  distributionCenter: values.activityDistributionCenter,
  electricityDistributor: values.activityDistributorEletricity,
  energyGeneration: values.activityEnergyGeneration,
  extractor: values.activityExtractor,
  farmCoop: values.activityFarmCoop,
  filmIndustry: values.activityFilm,
  finalConsumer: values.activityFinalConsumer,
  fuelDistributor: values.activityDistributorFuel,
  generalWarehouse: values.activityWarehouseGeneral,
  importer: values.activityImporter,
  industry: values.activityIndustry,
  itaipubiNacional: values.activityItaipu,
  maritimeService: values.activityMaritime,
  mealSupplier: values.activityMeal,
  nonProfitEntity: values.activityNonProfitEntity,
  pharmaDistributor: values.activityDistributorPharma,
  publicAgency: values.activityPublicAgency,
  religiousEstablishment: values.activityReligious,
  retail: values.activityRetail,
  ruralProducer: values.activityRural,
  securityPublicAgency: values.activitySecurity,
  service: values.activityService,
  stockWarehouse: values.activityWarehouseStock,
  telco: values.activityTelco,
  transporter: values.activityTransporter,
  waterDistributor: values.activityDistributorWater,
  wholesale: values.activityWholesale,
}
